name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        runner:
          - ${{ github.repository_owner == 'Changqing-JING' && 'ubuntu-24.04-arm' || 'atc-ubuntu-arm-latest' }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Show
        run: uname -a

      - name: Create test file
        run: echo "This is a test file created at $(date)" > test-file.txt

      - uses: actions/upload-artifact@v4
        if: env.GITHUB_SERVER_URL == 'https://github.com'
        with:
          name: test-artifact
          path: test-file.txt

      - uses: actions/upload-artifact@v3
        if: env.GITHUB_SERVER_URL != 'https://github.com'
        with:
          name: test-artifact
          path: test-file.txt
